PREFIX po: <http://purl.org/ontology/po/>
PREFIX slobr: <http://slobr.linkedmusic.org/terms/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bbc: <http://www.bbc.co.uk/programmes/>

select distinct ?segment ?title ?contributor ?name where {{
    graph <http://slobr.linkedmusic.org/EMS> {{
        VALUES ?segment  {{
            {segments}
        }} .

        ?segment dct:contributor ?contributor ;
            dct:title ?title .
        ?contributor rdfs:label ?name .
    }}
}}
order by ?segment

