PREFIX po: <http://purl.org/ontology/po/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX slobr: <http://slobr.linkedmusic.org/terms/>
PREFIX bbc: <http://www.bbc.co.uk/programmes/>

select distinct ?uri ?title ?date ?short_synopsis ?medium_synopsis ?long_synopsis ?image ?nextEpisode ?previousEpisode where {{
    graph <http://slobr.linkedmusic.org/EMS> {{
        {uri}
        ?uri a po:Episode; 
            dct:date ?date ;
            dct:title ?title ;
            po:short_synopsis ?short_synopsis ;
            po:medium_synopsis ?medium_synopsis ;
            po:long_synopsis ?long_synopsis ;
            dct:relation ?image ;
            slobr:peers ?peers .
        OPTIONAL {{
            ?peers slobr:nextEpisode ?nextEpisode .
        }}
        OPTIONAL {{
            ?peers slobr:previousEpisode ?previousEpisode .
        }}
    }}
}}
order by desc(?date) 
