PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dbp: <http://dbpedia.org/ontology/>
select ?birth ?birthPlace ?death ?deathPlace ?image ?bio
where  {{ 
    {linkedbrainz} 
    SERVICE <http://linkedbrainz.org/sparql> {{
            ?linkedbrainz owl:sameAs ?dbpedia .
    }}
    SERVICE <http://dbpedia.org/sparql> {{
              ?dbpedia  dbp:birthDate ?birth ;
                        dbp:birthPlace ?birthP ;
                        dbp:deathDate ?death ;
                        dbp:deathPlace ?deathP ;
                        foaf:depiction ?image ;
                        dbp:abstract ?bio .
              ?birthP rdfs:label ?birthPlace .
              ?deathP rdfs:label ?deathPlace .
              FILTER(langMatches(lang(?birthPlace), "en")) .
              FILTER(langMatches(lang(?deathPlace), "en")) .
              FILTER(langMatches(lang(?bio), "en")) .
    }}
}}


