# select all information on a particular entity
# if that entity has been SALT-matched to another entity, 
# also include that other entity's information

PREFIX salt: <http://slobr.linkedmusic.org/salt/>
PREFIX saltset: <http://slobr.linkedmusic.org/saltsets/>
PREFIX : <http://slobr.linkedmusic.org/>

SELECT DISTINCT ?uri ?p ?o WHERE {{ 
	BIND (<{sourceUri}> AS ?source) .
  VALUES ?datasets {{
		:EMS
		:SLICKMEM
	}}

	graph <{trustedGraph}> {{
		?source (:matchParticipant/^:matchParticipant)* ?uri .
	}}

	graph ?datasets {{ 
		?uri ?p ?o .
	}}
}}
